### ISSUE TITLE
请问一下，示例项目需要在RoboDK里配合打开哪个项目？

### ISSUE THREAD

**Issue by yanzixiang** [dathlin/RoboDKHelper#2]
我看代码里面并没有自动打开啊。
还有代码里面把所有关于是否已经连接的判断给注释掉了，不知为何。
官方的部分C#库，这个指的是哪里呢？我在官网上面没有找到C#使用的说明啊。

**Comment by dathlin** [comment]
![123124](https://user-images.githubusercontent.com/19341536/32415561-a51e1f82-c276-11e7-9435-823dc2cde787.png)
首先，取消了一些和软件很少使用的交互指令，自动打开也取消了，不适合做库。
判断是否连接，官方的库判断也是没什么意义的，其实本来就不用判断
官方的C#库还没完善好，我是内部人员拿的代码。
